### ISSUE TITLE
ImportError: No module named 'dr.settings.local'

### ISSUE THREAD

**Issue by charliedontsurf** [vintasoftware/django-react-boilerplate#149]
Followed install instructions, when trying to do initial migrate I get the following (my project is called dr)
```
(dr) mikey@mikey:~/dr/dr$ python manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/home/mikey/.virtualenvs/dr/lib/python3.5/site-packages/django/core/mangement/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/mikey/.virtualenvs/dr/lib/python3.5/site-packages/django/core/mangement/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/home/mikey/.virtualenvs/dr/lib/python3.5/site-packages/django/conf/__iit__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/mikey/.virtualenvs/dr/lib/python3.5/site-packages/django/conf/__iit__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/mikey/.virtualenvs/dr/lib/python3.5/site-packages/django/conf/__iit__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/mikey/.virtualenvs/dr/lib/python3.5/importlib/__init__.py", line 26, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'dr.settings.local'
(dr) mikey@mikey:~/dr/dr$ python manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/home/mikey/.virtualenvs/dr/lib/python3.5/site-packages/django/core/mangement/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/mikey/.virtualenvs/dr/lib/python3.5/site-packages/django/core/mangement/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/home/mikey/.virtualenvs/dr/lib/python3.5/site-packages/django/conf/__iit__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/mikey/.virtualenvs/dr/lib/python3.5/site-packages/django/conf/__iit__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/mikey/.virtualenvs/dr/lib/python3.5/site-packages/django/conf/__iit__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/mikey/.virtualenvs/dr/lib/python3.5/importlib/__init__.py", line 26, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'dr.settings.local'



```

**Comment by hugobessa** [comment]
@charliedontsurf are you sure you follow all these steps bellow? Is there a file named local.py in your settings folder? 
![boilerplate](https://user-images.githubusercontent.com/1779823/32691005-89738052-c6df-11e7-85ad-8e012d048e2a.png)

**Comment by charliedontsurf** [comment]
Hi, there is no ".env" file to copy, I am also not sure what good it is having a copy. I am only running a test project so if things break I do not mind!

**Comment by andersonresende** [comment]
1) You should copy `.env.example`to `.env`.
2) This `.env` is pointing to your `dr.settings.local`.
3) You can delete `.env.example` later.

**Comment by chocoelho** [comment]
Hi @charliedontsurf, did it work with the provided solutions?

**Comment by chocoelho** [comment]
Closed due to inactivity
